all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "admin"
    ansible_password: "admin"

prod:
  hosts:
    client1:
      ansible_host: 
      instance_1:
        name: WebApp
        port: 8080
        name_directory: webapp
        title_html: "Flavien"
